compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

pnpMode: loose

packageExtensions:
  mongoose@*:
    dependencies:
      events: "*"
  undici-types@*:
    dependencies:
      url: "*"
      events: "*"
      buffer: "*"
  "@types/node@*":
    dependencies:
      events: "*"
  "@types/mongodb@*":
    dependencies:
      bson: "*"
      events: "*"
  "@types/express@*":
    dependencies:
      serve-static: "*"
      events: "*"
      body-parser: "*"
      qs: "*"
  "@types/express-serve-static-core@*":
    dependencies:
      send: "*"
      events: "*"
      qs: "*"
      range-parser: "*"
  "@types/serve-static@*":
    dependencies:
      mime: "*"
  "@types/send@*":
    dependencies:
      mime: "*"
  mongodb-memory-server-core@*:
    dependencies:
      events: "*"
  mongodb@*:
    dependencies:
      events: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
